name: cc_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_phone_field: ^3.1.0
  toast: ^0.3.0
  #flutter_blue: ^0.8.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  sqflite: ^2.2.6
  adobe_xd: ^2.0.1
  flutter_svg: ^1.0.3
  get: ^4.6.5

flutter:
  uses-material-design: true
